# Generated by Django 4.2.16 on 2024-11-23 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportadora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='OrdemServico',
        ),
    ]
