# Generated by Django 4.2.16 on 2024-11-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportadora', '0003_rename_company_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
